AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Quarkus Native on AWS Lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 256


Resources:
  QuarkusNative:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      Runtime: provided.al2023
      CodeUri: gha/aws
      Handler: bootstrap.is.real.handler
      Layers:
        # Lambda Web Adapter (LWA)
        - arn:aws:lambda:eu-west-1:753240598075:layer:LambdaAdapterLayerX86:17
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          RUST_LOG: debug
          ASYNC_INIT: true
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          QUARKUS_OTEL_ENABLED: false
          QUARKUS_MICROMETER_EXPORT_OTLP_ENABLED: false
Outputs:
  FunctionUrl:
    Description: "Function URL of Quarkus Native"
    Value: !GetAtt QuarkusNativeUrl.FunctionUrl