AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Quarkus Native on AWS Lambda

Parameters:
  ArchCPU:
    Description: The Architecture CPU
    Type: String
    Default: x86-64
    AllowedValues:
      - x86-64
      - arm64
      - aarch64
    ConstraintDescription: must be a x86-64, arm64 or aarch64

Mappings:
  ArchitecturesMap:
    arm64:
      arch: arm64
      lwa: arn:aws:lambda:eu-west-1:753240598075:layer:LambdaAdapterLayerArm64:17
    aarch64:
      arch: arm64
      lwa: arn:aws:lambda:eu-west-1:753240598075:layer:LambdaAdapterLayerArm64:17
    x86-64:
      arch: x86_64
      lwa: arn:aws:lambda:eu-west-1:753240598075:layer:LambdaAdapterLayerX86:17

Globals:
  Function:
    Timeout: 20
    MemorySize: 256


Resources:
  QuarkusNative:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - !FindInMap [ArchitecturesMap, !Ref ArchCPU, "arch"]
      Runtime: provided.al2
      CodeUri: .
      Handler: bootstrap.is.real.handler
      Layers:
        # Lambda Web Adapter (LWA)
        - !FindInMap [ArchitecturesMap, !Ref ArchCPU, "lwa"]
      FunctionUrlConfig:
        AuthType: NONE
      LoggingConfig:
        LogFormat: JSON 
        ApplicationLogLevel: DEBUG 
        SystemLogLevel: INFO 
        LogGroup: !Ref QuarkusNativeLogGroup
      Environment:
        Variables:
          RUST_LOG: debug
          ASYNC_INIT: true
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
    Metadata:
      BuildMethod: makefile
  
  QuarkusNativeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/java-native-compilation-workshop/lambda/quarkus-native
      LogGroupClass: INFREQUENT_ACCESS
      RetentionInDays: 7

Outputs:
  FunctionUrl:
    Description: "Function URL of Quarkus Native"
    Value: !GetAtt QuarkusNativeUrl.FunctionUrl