
image:
  file: .gitpod.Dockerfile

tasks:
  - name: 03-springboot
    before: |
      cd 03-springboot
    init: |
      make build
  - name: 03-quarkus
    openMode: split-right
    before: |
      cd 03-quarkus
    init: |
      make build
  - name: Register Docker Cloud Builder
    command: |
      (
        set -e
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker buildx create --driver cloud $DOCKER_USERNAME/$DOCKER_BUILDER_NAME
        echo "Use Docker cloud builder :  --builder cloud-$DOCKER_USERNAME-$DOCKER_BUILDER_NAME"
      )
  - name: Start Grafana - LGTM
    before: |
      cd grafana
    init: |
      docker compose -f compose.lgtm.yml up -d --wait
  - name: Setup MUSL Toolchain (statically linked applications with Native Image)
    init: |
      bash scripts/setup-musl.sh

vscode:
  extensions:
    - redhat.java
    - VMware.vscode-spring-boot
    - redhat.vscode-quarkus
    - mhutchie.git-graph
    - vscjava.vscode-gradle
    - vscjava.vscode-maven
    - ms-vscode.makefile-tools
