
image:
  file: .gitpod.Dockerfile

tasks:
  - name: 03-springboot
    before: |
      cd 03-springboot
    init: |
      make build
  - name: 03-quarkus
    openMode: split-right
    before: |
      cd 03-quarkus
    init: |
      make build

vscode:
  extensions:
    - redhat.java
    - VMware.vscode-spring-boot
    - redhat.vscode-quarkus
