services:
  lgtm:
    image: grafana/otel-lgtm
    container_name: lgtm
    environment:
      ENABLE_LOGS_OTELCOL: "true"
    ports:
      - 3000:3000 # Grafana
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver