FROM container-registry.oracle.com/graalvm/native-image:24.0.0-ol9 AS builder

RUN microdnf install findutils

WORKDIR /code

COPY  gradle  ./gradle
COPY  gradlew *.gradle.kts ./
COPY  src ./src

RUN ./gradlew nativeCompile -PnativeExecutableLinkedMode=mostly

FROM gcr.io/distroless/base-debian12 AS application
COPY --from=builder /code/build/native/nativeCompile/spring-native /application
EXPOSE 8000
ENTRYPOINT ["/application"]