FROM container-registry.oracle.com/graalvm/native-image:24.0.0-ol9 AS builder

RUN microdnf install findutils

WORKDIR /code

COPY  gradlew ./
COPY  gradle  ./gradle
COPY  *.gradle.kts ./
COPY  src ./src

RUN ./gradlew nativeCompile

FROM gcr.io/distroless/java-base-debian12 AS application
COPY --from=builder /code/build/native/nativeCompile/spring-native /application
EXPOSE 8000
ENTRYPOINT ["/application"]