services:
  lgtm:
    image: grafana/otel-lgtm
    container_name: lgtm
    environment:
      ENABLE_LOGS_OTELCOL: "true"
    volumes:
      - ./dashboards/custom-dashboards.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/custom-dashboards.yaml
      - ./dashboards/grafana-dashboard-quarkus-micrometer-prometheus.json:/otel-lgtm/quarkus/grafana-dashboard-quarkus-micrometer-prometheus.json
      - ./dashboards/grafana-dashboard-quarkus-micrometer-otlp.json:/otel-lgtm/quarkus/grafana-dashboard-quarkus-micrometer-otlp.json
    ports:
      - 3000:3000 # Grafana
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver