name: Quarkus Application CLI CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - 03-quarkus-cli/**
      - .github/workflows/quarkus-cli.yml
      - .github/workflows/native-image.yml

jobs:
  build-native-image-and-container-image:
    secrets: inherit
    uses: ./.github/workflows/native-image.yml
    with:
      app-name: quarkus-native-cli
      app-path: 03-quarkus-cli
      app-native-image-path: build
      app-native-image-name: '*-runner'